/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Redeem: typeof import('./src/components/Redeem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPasswordInput: typeof import('vant/es')['PasswordInput']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
