/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'exception': RouteRecordInfo<'exception', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'gift': RouteRecordInfo<'gift', '/gift', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'records': RouteRecordInfo<'records', '/records', Record<never, never>, Record<never, never>>,
    '/records/NavBar': RouteRecordInfo<'/records/NavBar', '/records/NavBar', Record<never, never>, Record<never, never>>,
  }
}
